### ISSUE TITLE
Messed Up Water Placement

### ISSUE THREAD

**Issue by rawleyjrawley** [PrehistoricKingdom/feedback#53] opened 2021-01-30 00:29 UTC
After deleting water, then placing water on the same spot, there are jagged patches of land that spawn with it.

![20210129182024_1](https://user-images.githubusercontent.com/78240660/106340570-e2b72280-625f-11eb-82ac-fe699a1d20d9.jpg)

**Comment by Strix1758** [comment] 2021-01-30 01:45
![image](https://user-images.githubusercontent.com/78242309/106343131-d18c0700-629b-11eb-8550-8fe20d26557b.png)

Experienced the same problem. After deletion, the terrain seems to "save" the location of the waters' edge, which interferes with any new water painted in the same spot.

**Comment by DinoSteve93** [comment] 2021-01-30 08:56
Closing, duplicate of another water-related issue

**Closed by DinoSteve93** 2021-01-30 08:56 UTC
Labels: duplicate
