### ISSUE TITLE
subsequent mini aviary placement

### ISSUE THREAD

**Issue by Dinobob66mya** [PrehistoricKingdom/feedback#56] opened 2021-01-30 02:52 UTC
After placing a mini aviary, if I do anything else, I can no longer place mini aviaries

**Comment by Dinobob66mya** [comment] 2021-01-30 02:56
If another building is placed, I can place mini aviaries again

**Comment by DinoSteve93** [comment] 2021-01-30 08:55
Closing this, duplicate of another issue, but thanks for reporting <3

**Closed by DinoSteve93** 2021-01-30 08:55 UTC
Labels: duplicate
