### ISSUE TITLE
Modular Shrubbery And Trees Stay Selected

### ISSUE THREAD

**Issue by hadrosaurhero** [PrehistoricKingdom/feedback#46] opened 2021-01-29 22:50 UTC
Items in the shrubbery and tree menus stay selected when you click on one item and then click on another. Not found in other modular menus.

**Comment by DinoSteve93** [comment] 2021-01-30 09:51
Closing, the issue is a duplicate and it's been fixed. Thanks for reporting

**Closed by DinoSteve93** 2021-01-30 09:51 UTC
Labels: bug, ux
